name: carehub-backend

services:
  postgres:
    image: postgres:17
    container_name: carehub-postgres
    environment:
      POSTGRES_DB: carehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: carehub-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: carehub-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: