server:
  port: 8080

app:
  import:
    default-password: ${DEFAULT_PASSWORD:ChangeMe123@}

  api-prefix: /api/v1
  cors:
    allowed-origin-patterns:
      - http://localhost:*
      - http://127.0.0.1:*
      - https://api.fpthub.online
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
  seed:
    enabled: ${APP_SEED_ENABLED:true}
    admin:
      employee-code: ${ADMIN_EMPLOYEE_CODE}
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
      name: ${ADMIN_NAME}

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  config:
    import:
      - optional:file:.env.properties
      - optional:file:env.properties

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/carehub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root123}
    hikari:
      data-source-properties:
        TimeZone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
